global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "linear_regression_training"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "host.docker.internal:8000"